### ISSUE TITLE
Registered Webhooks only shows APP_UNINSTALLED

### ISSUE THREAD

**Issue by CoolTechYT** [kinngh/shopify-node-express-mongodb-app#11]

**Comment by CoolTechYT** [comment]
It is latest pull for repo. Fresh pull. No modifications have been made to the code. I just followed the setup guide, went to the registered webhooks page, and only saw the APP_UNINSTALLED there

The code for registering webhooks:

`Shopify.Webhooks.Registry.addHandlers({
  APP_UNINSTALLED: {
    path: "/webhooks/app_uninstalled",
    webhookHandler: appUninstallHandler,
  },
  CUSTOMERS_DATA_REQUEST: {
    path: "/webhooks/customers_data_request",
    webhookHandler: customerDataRequest,
  },
  CUSTOMERS_REDACT: {
    path: "/webhooks/customers_redact",
    webhookHandler: customerRedact,
  },
  SHOP_REDACT: {
    path: "/webhooks/shop_redact",
    webhookHandler: shopRedact,
  },
});`

**Comment by kinngh** [comment]
The GDPR webhooks never show up as registered. Infact, trying to register them would actually give you a failed response which is why in the [auth middleware](https://github.com/kinngh/shopify-node-express-mongodb-app/blob/4579ed30aba723996ad1f4da69831f0289a693f0/server/middleware/auth.js#L39) we exclude responses from GDPR topics. You set those up in your Admin and not here. These are added in to create routes and have functions ready for easy access for the devs.

If you try to register any other webhooks, you need to add in the right scope before you register the webhook for it or it's going to throw errors.

**Comment by kinngh** [comment]
It's just a generally known thing, I need to update the docs but there's this basic assumption that you've already ready `shopify-node-api` package docs and general dev docs from Shopify.Dev, so I have been omitting a lot of stuff to put certain groups of people into the habit of reading documentation.

**Comment by CoolTechYT** [comment]
Sure, no worries!
