### ISSUE TITLE
Question: How do you generate the files underneath _developer/types/ ?

### ISSUE THREAD

**Issue by egillanton** [kinngh/shopify-node-express-mongodb-app#116]
I am in need of a version for 2024-04 and would love to know the process of generating the webhooks.js file

**Comment by kinngh** [comment]
So about that. It's complicated. There's no documentation on how to, but you can hack it together via this repo that I use [@kinngh/shop-utils](https://github.com/kinngh/shop-utils) that has all the building blocks. It's pretty manual and I want to work on streamlining this, but since this only happens once every 3 months there's other things that get more attention.

And yes, I know 2024-01 types aren't thrown in just yet, but I'm working on streamlining the process in the same repo later this month so types can be generated better^
