### ISSUE TITLE
Why was the `@shopify/app-bridge` package deprecated from the boilerplate?

### ISSUE THREAD

**Issue by jonasmatuliauskas** [kinngh/shopify-node-express-mongodb-app#117]
Hi, kinngh 👋 

What was the motivation behind deprecating `@shopify/app-bridge` package? Ref: [commit](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/611ec0a60a6c8a1fd40fa547fea954f0c5d7c30d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L36)
 
As I understand, Shopify require AppBridge for the `Built for Shopify` badge: [docs](https://shopify.dev/docs/api/app-bridge/previous-versions/app-bridge-from-npm/app-setup#initialize-shopify-app-bridge-in-your-app) 

Edit: readability

**Comment by kinngh** [comment]
Hey hey!

Shopify moved on from `@shopify/app-bridge` and `@shopify/app-bridge-react` into using AppBridge CDN. If you were to take a look at the documentation from Shopify [here](https://shopify.dev/docs/api/app-bridge-library), you'd notice they're now using a `<script>` to initialize AppBridge instead of an npm package, which is exactly what my boilerplate does [here](https://github.com/kinngh/shopify-node-express-mongodb-app/blob/0d5e4b017c8e218587c20cefa69eb884844816aa/client/index.html#L5), which comes from [this env variable](https://github.com/kinngh/shopify-node-express-mongodb-app/blob/0d5e4b017c8e218587c20cefa69eb884844816aa/.env.example#L11). 

Also, AppBridge React has now been moved under `previous versions` on Shopify.dev's website, that you can find [here](https://shopify.dev/docs/api/app-bridge/previous-versions/app-bridge-from-npm/app-setup)

I hope this clears it up^
