### ISSUE TITLE
root url /* not working on install

### ISSUE THREAD

**Issue by robotshatemonkeys** [kinngh/shopify-node-express-mongodb-app#51]
When you install on a test shop from the Shopify Partner the root url "/" returns "There is nothing here". 
The only way to install is by going directly to /auth?shop=xyz

Shouldn't the Test Shop functionality work? 
My understanding is that when published the installation process will try to go the root URL and find nothing. 

If I enter /auth as the App URL on Shopify Partner, then the process will start looping.

**Comment by kinngh** [comment]
This is a pinned issue, I highly recommend checking for pinned issues before opening one.
- https://github.com/kinngh/shopify-node-express-mongodb-app/issues/48

In short, in dev mode since we are connecting to Vite before Express, it needs to be manually pushed via the `/auth?shop=abc.myshopify.com` url and is a problem only in Dev mode and works as expected in production.
